// constants.js
const resume = {
  personal: {
    name: "Manivas Medishetty",
    location: "Newark, DE 19702",
    phone: "+1-510-690-3800",
    email: "Manivas81@gmail.com",
    linkedin: "https://www.linkedin.com/in/manivas-m-456458106/",
  },
  summary: "Seasoned Full Stack Web Developer with extensive experience in developing and deploying web applications using React and Next.js for front-end and Node.js and Express for back-end. Skilled in optimizing performance and scalability with technologies such as AWS, Docker, and SQL databases. Proficient in implementing robust testing strategies using Jest and Mocha to ensure code quality and reliability.",
  skills: [
    "JavaScript",
    "ES6",
    "JSX",
    "PL/SQL",
    "Vue.js",
    "Angular",
    "React JS",
    "Node JS",
    "Express JS",
    "Redux",
    "JQuery",
    "Bootstrap",
    "WebPack",
    "Jira",
    "Oracle DB",
    "Mysql",
    "MongoDB",
    "Agile",
    "Waterfall",
    "GitHub",
    "Bit Bucket",
    "Code Quality",
    "Jest",
    "UI/UX Collaboration",
    "SSR",
  ],
  experience: [
    {
      company: "Capital One",
      title: "Full Stack Web Developer",
      duration: "Dec 2022 - Present",
      responsibilities: [
        "Developed responsive web applications using Vue.js and React, optimizing state management with Vuex and Redux for improved user experience.",
        "Engineered RESTful APIs with Node.js and TypeORM, optimizing MySQL queries leading to a 25% increase in database performance.",
        "Implemented scalable and maintainable solutions using JavaScript and TypeScript, ensuring type safety and reducing runtime errors.",
        "Automated unit testing using Jest and ViteTest, achieving 90% test coverage in all applications.",
        "Reduced manual testing efforts through Cypress-based automated functional and component testing, improving release reliability.",
        "Spearheaded the AWS Fargate migration, enhancing scalability, cutting operational costs, and boosting system availability.",
        "Architected a Micro UI-based system, facilitating a microservices architecture for independent deployment and scaling of features.",
        "Automated CI/CD pipelines using GitHub Actions and AWS, streamlining deployment processes and reducing release time.",
        "Managed repositories in GitHub, enforcing best practices in version control, branching strategies, and peer code reviews to ensure code quality and team collaboration.",
        "Coordinated agile development sprints using Jira, tracking issues and prioritizing tasks to ensure on-time delivery of key milestones.",
        "Collaborated closely with cross-functional teams (designers, product managers, QA), ensuring alignment with business goals and delivering comprehensive solutions.",
        "Communicated technical concepts effectively to non-technical stakeholders, gathering requirements and translating them into actionable development plans.",
        "Enhanced browser compatibility by integrating Babel, enabling the use of modern JavaScript features across diverse platforms.",
        "Created reusable development templates with Yeoman generator, improving consistency across projects and speeding up development time by 15%.",
        "Implemented contract testing to ensure seamless integration between microservices, improving system reliability and communication between services.",
        "Styled and optimized UIs using CSS, ensuring responsive design and cross-browser compatibility, which improved user engagement and satisfaction.",
      ],
    },
    {
      company: "Waterfield Technologies",
      title: "Senior Front End Developer",
      duration: "Feb 2018 - Mar 2020",
      responsibilities: [
        "Developed applications using React 17.0.0, TypeScript, JavaScript, Redux, HTML5, CSS, and Cucumber JS, enhancing user interface performance and reliability.",
        "Utilized the Twilio platform to develop a CRM application, improving client customer service capabilities.",
        "Developed a React plugin for agents to display and share customer notes, enhancing information sharing and customer service efficiency.",
        "Maintained state in Redux stores and dispatched actions, ensuring seamless data flow and application stability.",
        "Worked with React components, forms, events, keys, router, and Flux concepts to enhance application functionality and user experience.",
        "Implemented an event bus that allowed communication between components in a PubSub-style, enhancing component interaction and data flow.",
        "Created and used reducers that received actions to modify the store state tree, improving state management and application performance.",
        "Implemented drag and drop functionality for a plugin using React-Draggable, enhancing user interaction and ease of use.",
        "Developed functional components to render layouts for agents on the application, improving user interface customization.",
        "Utilized Material UI icons to implement edit, delete, and dropdown functionality, enhancing application usability and navigation.",
        "Utilized promises to retrieve data from the backend and perform RESTful services, enhancing data handling efficiency.",
        "Used Figma for creating mocks and designs, successfully implementing React UI components to improve user interface consistency.",
        "Utilized Bitbucket for version control, regularly pushing and reviewing code to ensure code quality and collaboration.",
      ],
    },
    {
      company: "Executive Options LLC",
      title: "UI Developer",
      duration: "Mar 2020 - Dec 2022",
      responsibilities: [
        "Developed an application using Angular 12, TypeScript, HTML 5, CSS 3, Karma, Jasmine, Docker, AWS, and Node.js, resulting in a 25% increase in user engagement due to enhanced interface performance and reliability.",
        "Created reusable components and services to consume Node APIs using component-based architecture with Angular 12, which streamlined development processes and reduced code redundancy.",
        "Utilized new features of Angular 12 like Nullish Coalescing, styling improvements, and HTTP improvements, leading to more efficient code and better application performance.",
        "Implemented Template Driven and Reactive forms for form validation on server and client, ensuring robust data integrity and enhancing user efficiency.",
        "Implemented unit test cases using Jasmine and Karma to cover 100% functionality of each component.",
        "Developed APIs with Node.js to authenticate and validate user login credentials.",
        "Onboarded Node.js APIs in AWS cloud environment for East and West regions and created route 53 certificate.",
        "Utilized GIT Hub to deploy and review the code and manage the versions.",
        "Implemented Continuous Integration and Deployment (CI/CD) with Jenkins and Docker, achieving a 30% increase in deployment speed and reducing errors by 25%.",
        "Analyzed API logs using Splunk to successfully identify and resolve issues, enhancing application reliability.",
      ],
    },
    {
      company: "Capital One",
      title: "UI Developer",
      duration: "Feb 2018 - Mar 2020",
      responsibilities: [
        "Utilized technologies like Vue.js 2.6, Node.js, JavaScript, HTML, CSS, Java, Spring Boot, Jest, Chai, Cucumber.js, Docker, Cypress, Gherkin, and Amazon AWS to develop the application, enhancing its performance and scalability.",
        "Worked with Vue router, Vue CLI, Vuex, and Nuxt.js to streamline the development process, improving application routing and state management.",
        "Wrote unit test cases using Junit for API and acceptance tests using WireMock, Handlebars.js, and Cucumber.js, improving code reliability.",
        "Worked on writing the integration test cases using Cucumber.js, Docker and Gherkin to record the scenarios for the implementation.",
        "Implemented microservices utilizing multiple APIs across the application, enhancing system modularity and efficiency.",
        "Deployed Docker-contained Spring Boot microservice into AWS EC2 container service using AWS Admin console, ensuring seamless application deployment.",
        "Leveraged AWS services including S3, Lambda, and EC2 to optimize infrastructure scalability, leading to a 20% increase in system performance and cost efficiency.",
        "Developed menu and navigation layouts using CSS Flexbox and Bootstrap Grids, improving site navigation and user accessibility.",
        "Implemented WCAG 2.0 rules to enhance accessibility, ensuring compliance with industry standards.",
        "Utilized AXE tool and Chrome Developer Tools for ADA testing and screen reader functionality, improving application accessibility.",
        "Implemented Continuous Integration and Deployment (CI/CD) using Jenkins and Docker, enhancing deployment efficiency and reliability.",
        "Utilized Splunk to check logs for APIs, improving issue investigation and resolution efficiency.",
      ],
    },
    {
      company: "PG&E",
      title: "UI Developer",
      duration: "Feb 2018 - Mar 2020",
      responsibilities: [
        "Developed the application using Angular 6, TypeScript, HTML5, and CSS/CSS3, enhancing user interface responsiveness and user experience.",
        "Worked on Angular directives, filters, services, templates, events, and injectors, improving code modularity and maintainability.",
        "Developed forms in the applications using both Template Driven and Data Driven approaches with Angular forms module, ensuring efficient data handling and validation.",
        "Created custom directives, components, and filters for the application, enhancing functionality and user interaction.",
        "Utilized REST services to retrieve data from the backend, ensuring seamless data integration and application performance.",
        "Implemented libraries like ag-grid and features like row selection, enhancing data interaction and user experience.",
        "Developed Responsive Design UI, Rich REST Service Applications, Single Page Applications (SPA) and HTML Wireframes using HTML5 Grid Structures/LAYOUTs, CSS3 Media Queries, Twitter Bootstrap.",
        "Used standard security technology like SSL (Security Sockets Layer) to establish an encrypted link between a web server and a browser, ensuring secure data transmission.",
        "Enhanced user interface design by applying CSS styling techniques, including positioning, text, border, margin, sprites, padding, tables, pseudo elements, and classes, improving visual consistency and user experience.",
        "Wrote Karma unit tests to verify JavaScript utility routines and used Istanbul for code coverage, ensuring application reliability and performance.",
      ],
    },
    {
      company: "Object Edge",
      title: "UI Developer",
      duration: "Feb 2018 - Mar 2020",
      responsibilities: [
        "Developed webpages using React 16.0.0, Redux, Node version 9.11.1, SCSS, and JavaScript, enhancing user experience and performance.",
        "Created user interfaces using React HOC and Flux/Redux for SPA development, improving application efficiency and user engagement.",
        "Implemented various Bootstrap components like Accordion, Date-picker, and Modal to enhance the functionality and responsiveness of the user interface.",
        "Utilized React JS components, Forms, Events, Keys, Router, Animations, and Flux concept to build dynamic and interactive web applications, enhancing user interaction.",
        "Implemented stable React components and stand-alone functions, improving future page development efficiency and maintainability.",
        "Wrote styling scripts using SCSS for styling and aligning content, which improved the visual consistency and user experience of the application.",
        "Enhanced React Observables with Redux, React-router, and Redux-thunk, leading to improved state management and navigation efficiency.",
        "Used POST and GET methods to retrieve and submit user data on the payment page via web API, ensuring seamless data transfer to the backend.",
        "Revamped and rewrote the front-end using React JS, Redux, Saga, and Webpack, improving application performance and user experience.",
        "Used React-Router techniques and Axios service to retrieve data from the server in the background, enhancing page interactivity and user experience.",
        "Developed unit test cases using Jasmine and Karma to ensure the reliability of pipes, services, and components, improving code quality and reducing bugs.",
        "Deployed code to various environments including SIT, QA, Development, and Production, ensuring smooth transitions and minimal downtime.",
        "Helped the team to understand the architecture of the project and involved in the architecture.",
      ],
    },
    {
      company: "Vedic Soft",
      title: "UI Developer",
      duration: "Feb 2018 - Mar 2020",
      responsibilities: [
        "Created dynamic website designs and programmed applications using Angular-JS, HTML, Bootstrap, CSS, and JavaScript, resulting in enhanced user engagement and application responsiveness.",
        "Implemented functionalities for adding, deleting, updating, bulk updating, and bulk deleting users, enhancing user management efficiency.",
        "Implemented Angular form validations and used Bootstrap to show error, warning and info messages.",
        "Configured the routing service using Angular-JS router, streamlining navigation and improving application flow.",
        "Used Angular Resource and http services to retrieve the data from server and to display the content on the browser and took part in creating custom reusable components.",
        "Developed Angular-JS directives to create reusable UI components, enhancing code efficiency and maintainability.",
        "Created HTML and JavaScript for client-side presentation and data validation, improving user experience and data accuracy.",
      ],
    },
  ],
  education: [
    {
      degree: "Master, Computer Science",
      institution: "Northwestern Polytechnic University",
      duration: "Aug 2015 - 2016",
    },
    {
      degree: "Bachelor's, Computer Science",
      institution: "JNTUH",
      duration: "Mar 2011 - Mar 2014",
    },
  ],
  certifications: ["AWS Certified Developer - Associate: Amazon AWS Services"],
  yearsOfExperience: {
    total: 5, // Total years of experience
    technologies: {
      "JavaScript": 5,
      "React": 4,
      "Vue.js": 3,
      "Node.js": 4,
      "Angular": 3,
      "AWS": 3,
      "Docker": 3,
      "SQL": 4,
      "TypeScript": 3,
      "Redux": 4,
      "HTML/CSS": 5,
      "Git": 5,
      "Jest": 3,
      "Cypress": 2,
    },
  },
};

module.exports = {
  resume,
};